# Site settings
title: ian
header-img: img/home-bg.jpg
email: ian_123@126.com
description: "ian"
baseurl: ""
url: "www.yinyien.com"
# twitter_username: SBootstrap
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
